apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: krebseng-www-redirect
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/permanent-redirect: https://krebseng.com.br
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01

spec:
  tls:
    - hosts:
      - www.krebseng.com.br
      secretName: krebseng-www-tls
  rules:
    - host: www.krebseng.com.br
      http:
        paths:
          - path: /
            backend:
              serviceName: ambassador
              servicePort: 80
